### PR TITLE
[release-4.15] OCPBUGS-27910: Resolve all outstanding snyk vulnerabilities

### PR DESCRIPTION
**Pull request by dlom**
/hold

### CODE REVIEW

**Comment by dlom** [comment]
/retitle [release-4.15] OCPBUGS-27900: Resolve all outstanding snyk vulnerabilities

**Comment by dlom** [comment]
/retitle [release-4.15] OCPBUGS-27910: Resolve all outstanding snyk vulnerabilities

**Comment by jianping-shu** [comment]
Regression tested with cluster-bot build.
AWS cluster installed successfully.
Regression tests OCP-36498/50869/48360/34470 passed.

**Comment by dlom** [comment]
Ironic that this happens on a PR designed to remove detected vulnerabilities, but snyk is tripping on a vuln that (as of time of writing) has no published fix: https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2-6173321

/override ci/prow/security
/unhold

**Pull request merged**
