### PR TITLE
Bug 1907613: operator: remove odicdiscoveryendpoint controller

### PR DESCRIPTION
**Pull request by sjenning**
pick https://github.com/openshift/cloud-credential-operator/pull/276 to `release-4.6`

@joelddiaz @dgoodwin @marun

### CODE REVIEW

**Review by joelddiaz — COMMENTED** [review]
/lgtm

**Review by joelddiaz — COMMENTED** [review]
/lgtm

**Comment by russellb** [comment]
(patch manager) 4.6 blocker identified, so pulling unmerged patches from the queue

**Pull request merged**
