### PR TITLE
[release-4.9] Bug 1992563: update alerts with summary and descriptions

### PR DESCRIPTION
**Pull request by joelddiaz**
As requested in the alerting consistency enhancement
https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md,
update the prometheus alerts in the repo to add summary and description
annotations to each alert.

Manual cherry-pick/backport of #395

### CODE REVIEW

**Comment by hardys** [comment]
@joelddiaz this needs the backport-risk-assessed label, but it seems this repo is [lacking the necessary config](https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/cloud-credential-operator/_pluginconfig.yaml#L3) and should be updated similar to other repos e.g see [example](https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/cluster-cloud-controller-manager-operator/_pluginconfig.yaml#L9..L15)

**Comment by jianping-shu** [comment]
/label cherry-pick-approved

Tested as comment in Bug 1992563.

**Pull request merged**
