### PR TITLE
Add manifest annotations for hosted deployment exclusions

### PR DESCRIPTION
**Pull request by csrwng**
Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252

### CODE REVIEW

**Comment by joelddiaz** [comment]
@csrwng so how do in-cluster components get cloud credentials for the hosted control-plane environment?

**Comment by csrwng** [comment]
For now they don’t. IBM public cloud uses its own kube cloud provider for storage and lb’s. And they do their own machine management.

**Comment by joelddiaz** [comment]
it looks like we're good to merge after the format of the annotation is finalized

**Comment by csrwng** [comment]
@joelddiaz the CVO PR has merged, this should be good to go

**Pull request merged**
