### PR TITLE
OCPBUGS-38951: Follow-up bug fixes for CCO-572

### PR DESCRIPTION
**Pull request by dlom**
/assign @jstuever

### CODE REVIEW

**Comment by jianping-shu** [comment]
@dlom I had a test on this PR.
After creating the root credentials secret (work around for [OCPBUGS-37952](https://issues.redhat.com/browse/OCPBUGS-37952)), it worked and the test case [OCP-75429](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-75429) was updated.
one thing to mention is that CredentialsProvisionFailure set to True for the CredentialsRequest with audience etc. From the logs, it is the side effect for creating the credentials secret, not a real issue.

jianpingshu@jshu-mac ~ % oc -n openshift-cloud-credential-operator get -o json credentialsrequests | jq -r '.items[] | select(tostring | contains("InfrastructureMismatch") | not) | .metadata.name as $n | .status.conditions // [{type: "NoConditions"}] | .[] | .type + "=" + .status + " " + $n + " " + .reason + ": " + .message' | sort
CredentialsProvisionFailure=False cloud-credential-operator-gcp-ro-creds CredentialsProvisionSuccess: successfully granted credentials request
CredentialsProvisionFailure=False openshift-cloud-network-config-controller-gcp CredentialsProvisionSuccess: successfully granted credentials request
CredentialsProvisionFailure=False openshift-gcp-ccm CredentialsProvisionSuccess: successfully granted credentials request
CredentialsProvisionFailure=False openshift-gcp-pd-csi-driver-operator CredentialsProvisionSuccess: successfully granted credentials request
CredentialsProvisionFailure=False openshift-image-registry-gcs CredentialsProvisionSuccess: successfully granted credentials request
CredentialsProvisionFailure=False openshift-ingress-gcp CredentialsProvisionSuccess: successfully granted credentials request
CredentialsProvisionFailure=False openshift-machine-api-gcp CredentialsProvisionSuccess: successfully granted credentials request
CredentialsProvisionFailure=True test-creds CredentialsProvisionFailure: failed to grant creds: error determining whether a credentials update is needed

logs:
time="2024-08-12T00:59:53Z" level=debug msg="target secret exists" actuator=gcp cr=openshift-cloud-credential-operator/test-creds
time="2024-08-12T00:59:53Z" level=error msg="cloud cred secret not yet annotated" actuator=gcp cr=openshift-cloud-credential-operator/test-creds secret=kube-system/gcp-credentials 
time="2024-08-12T00:59:53Z" level=debug msg="error retrieving cloud credentials secret" error="cannot proceed without cloud cred secret annotation"
time="2024-08-12T00:59:53Z" level=error msg="error determining whether a credentials update is needed" actuator=gcp cr=openshift-cloud-credential-operator/test-creds error="cannot proceed without cloud cred secret annotation"

**Comment by dlom** [comment]
@jianping-shu have you tried creating read-only credentials as a workaround as well?

**Comment by jianping-shu** [comment]
@dlom I think the gcp read-only credential already exists after gcp wif cluster installs. But from cco logs, it still reported below. I'll double check this.

time="2024-08-11T03:46:11Z" level=warning msg="read-only creds not found, using root creds client" actuator=gcp cr=openshift-cloud-credential-operator/openshift-cloud-network-config-controller-gcp secret=openshift-cloud-credential-operator/cloud-credential-operator-gcp-ro-creds

**Comment by jianping-shu** [comment]
@dlom Checked on the cluster. There's read-only creds but still log "read-only creds not found". Here is full log for one syncing.
jianpingshu@jshu-mac ~ % oc get secret cloud-credential-operator-gcp-ro-creds -n openshift-cloud-credential-operator
NAME                                     TYPE     DATA   AGE
cloud-credential-operator-gcp-ro-creds   Opaque   1      6h35m

time="2024-08-15T00:35:55Z" level=info msg="syncing credentials request" controller=credreq cr=openshift-cloud-credential-operator/openshift-image-registry-gcs
time="2024-08-15T00:35:55Z" level=debug msg="found secret namespace" controller=credreq cr=openshift-cloud-credential-operator/openshift-image-registry-gcs secret=openshift-image-registry/installer-cloud-credentials
time="2024-08-15T00:35:55Z" level=debug msg="timed token access cluster detected: true, so not trying to provision with root secret" controller=credreq cr=openshift-cloud-credential-operator/openshift-image-registry-gcs secret=openshift-image-registry/installer-cloud-credentials
time="2024-08-15T00:35:55Z" level=debug msg="target secret does not exist" actuator=gcp cr=openshift-cloud-credential-operator/openshift-image-registry-gcs
time="2024-08-15T00:35:55Z" level=debug msg="running sync" actuator=gcp cr=openshift-cloud-credential-operator/openshift-image-registry-gcs
time="2024-08-15T00:35:55Z" level=debug msg="Loading infrastructure name: jshu815-bbz9t" actuator=gcp cr=openshift-cloud-credential-operator/openshift-image-registry-gcs
time="2024-08-15T00:35:55Z" level=debug msg="loading GCP read-only credentials from secret" actuator=gcp cr=openshift-cloud-credential-operator/openshift-image-registry-gcs secret=openshift-cloud-credential-operator/cloud-credential-operator-gcp-ro-creds
time="2024-08-15T00:35:55Z" level=warning msg="read-only creds not found, using root creds client" actuator=gcp cr=openshift-cloud-credential-operator/openshift-image-registry-gcs secret=openshift-cloud-credential-operator/cloud-credential-operator-gcp-ro-creds
time="2024-08-15T00:35:55Z" level=debug msg="loading GCP credentials from secret" actuator=gcp cr=openshift-cloud-credential-operator/openshift-image-registry-gcs secret=kube-system/gcp-credentials
time="2024-08-15T00:35:55Z" level=error msg="error creating GCP client" error="Secret \"gcp-credentials\" not found"
time="2024-08-15T00:35:55Z" level=error msg="error determining whether a credentials update is needed" actuator=gcp cr=openshift-cloud-credential-operator/openshift-image-registry-gcs error="unable to check whether credentialsRequest needs update"

**Comment by dlom** [comment]
@jianping-shu I have pushed another change to this branch that should fix the error.  Please give it a try

**Comment by jianping-shu** [comment]
@dlom I tested with cluster-bot build based on the new commit and it works fine now.
Test case [OCP-75429 - Test the STS OLM functionality of GCP](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-75429) has been updated.
I also did simple regression test on mint/passthrough mode and no issue.
But how about [OCPBUGS-37952](https://issues.redhat.com/browse/OCPBUGS-37952)? 
Are you going to fix the bug by this PR for 4.18/4.17 and do manual back-porting for pre-4.17 releases?

**Comment by dlom** [comment]
/retitle OCPBUGS-38951: Follow-up bug fixes for CCO-572

**Pull request merged**
