### PR TITLE
Bug 2118625: Refactor Nutanix plugin to use external credentials structs

### PR DESCRIPTION
**Pull request by thunderboltsid**
To keep structures in sync and in one place, the credential structs
will be fetched from the Prism Go client. The PR also fixes an
edgecase where ccoctl panics when processing Nutanix credentials
requests.

### CODE REVIEW

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Comment by thunderboltsid** [comment]
@akhil-rane should we file a BZ here or wait for the relevant approval labels?

**Comment by akhil-rane** [comment]
@thunderboltsid I think we should go ahead and file the BZ for the panic

**Pull request merged**
