### PR TITLE
OCPBUGS-37834: Resolve SNYK errors in security job.

### PR DESCRIPTION
**Pull request by jstuever**

### CODE REVIEW

**Comment by jstuever** [comment]
Depends on https://github.com/openshift/release/pull/55485

**Comment by jstuever** [comment]
/override ci/prow/e2e-aws-ovn ci/prow/e2e-upgrade
This is not a code change, the results of these jobs are irrelevant.

**Comment by huangmingxia** [comment]
/label cherry-pick-approved 

I have done regression tests on version 4.13, and they passed verification.

**Pull request merged**
