### PR TITLE
Bug 1855625: vendor in updated golang/x/text

### PR DESCRIPTION
**Pull request by joelddiaz**
fixes infinite loop possibility

### CODE REVIEW

**Comment by gregsheremeta** [comment]
who can review this?

**Comment by joelddiaz** [comment]
> who can review this?

just about anyone on the team can review this. it is just vendoring a newer version of the affected package to receive the fix.

**Comment by joelddiaz** [comment]
looks like another PR already pulled in this change and merged before openshift/cloud-credential-operator#227

**Comment by sdodson** [comment]
/reopen
wondering if this should have a merge conflict?

**Pull request closed without merging**
