### PR TITLE
update to release.openshift.io/feature-set to match OCP 4.12

### PR DESCRIPTION
**Pull request by deads2k**
This was added in
https://github.com/openshift/cluster-version-operator/pull/821 to allow
more featuresets and allow for a future migration to include actual gates

/cc @wking

### CODE REVIEW

**Comment by akhil-rane** [comment]
assign @jeana-redhat @jianping-shu @davemulford

**Comment by jeana-redhat** [comment]
- I think this means all instances (there are not a ton) of `release.openshift.io/feature-gate` need to be updated to `release.openshift.io/feature-set` - is that correct?
- Is this OCP 4.12+?

**Comment by jianping-shu** [comment]
Build image w/ cluster bot.
Tested w/ [OCP-48059 ](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-48059), annotation in CredentialsRequest is "feature-set".
[cloud-user@preserve-for-hive-test credrequests-aws]$ grep TechPreviewNoUpgrade *
0000_30_cluster-api_00_credentials-request.yaml:    release.openshift.io/feature-set: TechPreviewNoUpgrade

**Comment by jeana-redhat** [comment]
Based on @wking's :+1: I am approving with the impact understood as just s/`release.openshift.io/feature-gate`/`release.openshift.io/feature-set` in 4.12+ docs

/label docs-approved

**Comment by jeana-redhat** [comment]
@deads2k does there happen to be a dev-side Jira card that captures this? Just looking to see if there is a thing I can tie a docs card to.

**Pull request merged**
