### PR TITLE
[release-4.16] OCPBUGS-45939: Add AWS region to aws-pod-identity-webhook

### PR DESCRIPTION
**Pull request by swghosh**
Manual cherry-pick of #799

### CODE REVIEW

**Comment by swghosh** [comment]
This one can be directly cherry-picked onto release-4.15, 4.14 for further backports (without any conflicts).
/cherrypick release-4.15, release-4.14

**Review by jstuever — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Comment by jianping-shu** [comment]
Verified with cluster-bot build 4.16.0-0.ci.test-2024-12-16-014850-ci-ln-747tpjk-latest.
aws sts cluster installed successfully and regression tests passed.
cert-mananger 1.15 installed and OCP-62500 passed.

**Pull request merged**
