### PR TITLE
CCO-73: Add command to delete resources created by ccoctl 

### PR DESCRIPTION
**Pull request by akhil-rane**
`ccoctl create` creates resources with the following tag

`openshift.io/cloud-credential-operator/<name-prefix>: owned`

This command takes name-prefix and region as input and deletes all
the resources with the above tag

### CODE REVIEW

**Comment by akhil-rane** [comment]
/hold

wait for #306

**Comment by akhil-rane** [comment]
@joelddiaz I could not think of good unit tests here except aws delete calls failing and giving errors. I am not sure if adding them will be useful. Let me know what you think.

**Review by joelddiaz — COMMENTED** [review]
/lgtm

**Comment by akhil-rane** [comment]
/unhold

#306 has merged

**Comment by akhil-rane** [comment]
@joelddiaz resolved merge conflicts. Need lgtm again.

**Review by joelddiaz — COMMENTED** [review]
/lgtm

**Pull request merged**
