### PR TITLE
OCPBUGS-32898: Upgrade go-jose module to 2.6.3

### PR DESCRIPTION
**Pull request by dlom**
Upgrade go-jose module to 2.6.3

### CODE REVIEW

**Comment by dlom** [comment]
/retitle OCPBUGS-32898: Upgrade go-jose module to 2.6.3

**Review by jstuever — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Comment by jianping-shu** [comment]
Verified with cluster-bot build.
AWS STS cluster installed successfully.
Regression tested with OCP-36498/34470/48360/50869.

**Pull request merged**
