### PR TITLE
OCPBUGS-36030: IBM/go-sdk-core update to v5.17.4

### PR DESCRIPTION
**Pull request by jstuever**
Update IBM/go-sdk-core to v5.17.4 in order to update hashicorp/go-retryablehttp to v0.7.7

### CODE REVIEW

**Comment by jstuever** [comment]
/override ci/prow/security 
This is being tracked and resolved elsewhere.

**Comment by jianping-shu** [comment]
Verified with cluster-bot build 4.15.0-0.ci.test-2024-07-18-114412-ci-ln-ltgr0tt-latest.
AWS STS cluster installed successfully and healthy. Regression tested OCP-36498/
50869/48360/34470/64885.

**Pull request merged**
