### PR TITLE
TRT-481: fix: order conditions by type to limit un-needed updates

### PR DESCRIPTION
**Pull request by eggfoobar**
Sorting status arrays to avoid un-needed updates.

Signed-off-by: ehila <ehila@redhat.com>

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Yeah, we should totally be doing this. I'm surprised we weren't already.

/assign @akhil-rane

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Comment by akhil-rane** [comment]
Thanks for this PR @eggfoobar

**Comment by akhil-rane** [comment]
No change in functionality. 

/label px-approved
/label docs-approved

**Comment by akhil-rane** [comment]
@jianping-shu this will need a QE review to check if status fields are sorted as expected

**Comment by jianping-shu** [comment]
The status.conditions are listed in order of type Available, Degraded, Progressing, Upgradeable in past testing logs. I thought it was already sorted before.
Made cluster-bot build and verified with [OCP-45975](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-45975)

**Pull request merged**
