### PR TITLE
OCPBUGS-36027: IBM/go-sdk-core update to v5.17.4

### PR DESCRIPTION
**Pull request by jstuever**
Update IBM/go-sdk-core to v5.17.4 in order to update hashicorp/go-retryablehttp to v0.7.7

### CODE REVIEW

**Comment by jstuever** [comment]
/override ci/prow/security 
These issues are being tracked in other bugs.

**Comment by jstuever** [comment]
/override ci/prow/security
These are to be handled elsewhere.

**Comment by jianping-shu** [comment]
Verified with cluster-bot build 4.12.0-0.ci.test-2024-07-29-063447-ci-ln-ctxswlk-latest.
AWS STS cluster installed successfully and healthy. Regression tested OCP-36498/
50869/48360/34470.

**Pull request merged**
