### PR TITLE
allow skipping leader election

### PR DESCRIPTION
**Pull request by joelddiaz**
When hard-stopping a debugging session, the leader election cleanup doesn't get to run. Provide a way to skip all the leader election startup to speed up the development loop.

### CODE REVIEW

**Comment by joelddiaz** [comment]
> Do we need a doc update for this in [Developer Instructions](https://github.com/openshift/cloud-credential-operator#developer-instructions)?

The docs don't really address running with a debugger (which is the only reason I find this to be useful)... As long as CCO is shut down properly there shouldn't be any unnecessary waiting for leader elections, right?

**Comment by akhil-rane** [comment]
> > Do we need a doc update for this in [Developer Instructions](https://github.com/openshift/cloud-credential-operator#developer-instructions)?
> 
> The docs don't really address running with a debugger (which is the only reason I find this to be useful)... As long as CCO is shut down properly there shouldn't be any unnecessary waiting for leader elections, right?

Yes, if CCO is shutdown properly there is no waiting :)

**Pull request merged**
