### PR TITLE
Bug 2066403: Remove Azure mint mode support as Active Directory Graph API will be sunset

### PR DESCRIPTION
**Pull request by abutcher**

### CODE REVIEW

**Review by suhanime — COMMENTED** [review]
/lgtm

/label backport-risk-assessed

/assign @jianping-shu

**Comment by jianping-shu** [comment]
Tested with OCP-47143 (with registry.build01.ci.openshift.org/ci-ln-yg7rdtb/release:latest, 4.6 image based on the PR), passed
Tested with OCP-47144 and OCP-47159 (upgrade from 4.6 version whose default mode is "mint" to registry.build01.ci.openshift.org/ci-ln-yg7rdtb/release:latest, 4.6 image based on the PR), passed

**Pull request merged**
