### PR TITLE
Bug 1883691: Add validation for logLevel

### PR DESCRIPTION
**Pull request by dmage**
openshift/api#736 added restrictions for logLevel values. This PR vendors new openshift/api to get new CRDs.

### CODE REVIEW

**Comment by dmage** [comment]
/retitle Bug 1883691: Add validation for logLevel

**Comment by dgoodwin** [comment]
Sorry, needs a merge conflict update. :(

**Comment by dgoodwin** [comment]
@dmage can you resolve these conflicts so this will merge.

**Comment by dmage** [comment]
@dgoodwin openshift/api was bumped by #260. Nothing else is needed.

**Pull request closed without merging**
