### PR TITLE
CCO-525: Azure workload identity doc updates

### PR DESCRIPTION
**Pull request by jstuever**
- Converted numbered lists to use dynamic numbering.
- Updated install steps to take advantage of oc --included option when extracting credential requests.
- Switched to rebooting machine config pools instead of restarting all pods.

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
/hold
In case anyone else wishes to review too.

**Comment by julienlim** [comment]
OCPSTRAT-1185 is the feature JIRA for this one.

**Comment by jstuever** [comment]
/retitle CCO-525: Azure workload identity doc updates

**Comment by dlom** [comment]
/lgtm

Should be good to unhold at your leisure @jstuever

**Pull request merged**
