### PR TITLE
Bug 2058270: Remove Azure mint mode support as Active Directory Graph API will be sunset

### PR DESCRIPTION
**Pull request by 2uasimojo**
Manual backport of #453.

---

Migrate away from depending on the Azure Active Directory Graph API since it will be sunset in June 2022.

* [x]  No more mint mode for Azure. So continue supporting passthrough and manual mode as the only supported modes on Azure.
* [x]  The implementation is to always mark the Azure root secret as passthrough, and pivot a live running originally-mint cluster to passthrough mode.
* [x]  Overwrite existing Secrets with the content found in kube-system/azure-credentials (we can assume this as removing the root creds was never supported in Azure).
* [x]  Try to clean up previously minted App Registrations / Service Principals (while the Azure AD Graph API still works), but treat errors as non-fatal (just set a condition on the CredentialsRequest).
* [x]  Update test cases.

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/assign @jianping-shu 

for cherry-pick approval

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Comment by jianping-shu** [comment]
Verified [OCP-47143](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-47143) with cluster-bot build (launch 4.8-ci,openshift/cloud-credential-operator#454 azure)

Verified [OCP-47144](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-47144) and [OCP-47159](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-47159) with upgrade from 4.8.0-0.nightly-2022-02-26-041348 to 4.10.0-0.nightly-2022-02-24-141514

Passed

**Comment by jianping-shu** [comment]
@2uasimojo @akhil-rane 
Th document part change is also in another PR like 4.9, right?

**Comment by akhil-rane** [comment]
> @2uasimojo @akhil-rane Th document part change is also in another PR like 4.9, right?

It is included in the same PR as a commit. We did the same for 4.9

**Comment by jianping-shu** [comment]
OK. I checked the doc changes, no issue.

/label cherry-pick-approved

**Review by akhil-rane — APPROVED** [review]

**Pull request merged**
