### PR TITLE
OCPBUGS-37061: Update to azidentity v1.7.0

### PR DESCRIPTION
**Pull request by jstuever**

### CODE REVIEW

**Comment by jstuever** [comment]
/override ci/prow/security
These issues are being tracked in other bugs.

**Comment by jianping-shu** [comment]
Verified with cluster-bot build 4.15.0-0.ci.test-2024-07-29-064247-ci-ln-1bjjp6b-latest.
Azure cluster with Microsoft Entra Workload ID installed successfully.
Regression tested with OCP-50869/34470/66538/69971.

**Pull request merged**
