### PR TITLE
[release-4.9] Bug 2024751: pod-identity-webhook starts without tls

### PR DESCRIPTION
**Pull request by sanchezl**
Build with go 1.16.

### CODE REVIEW

**Comment by sanchezl** [comment]
/assign @joelddiaz 

This PR will need to merge in before #423.

**Review by joelddiaz — COMMENTED** [review]
/lgtm

**Comment by sanchezl** [comment]
1.  If the Bugzilla associated with the PR has the "FastFix" keyword, the subjective assessment on the issue has already been done and a customer is impacted. These PRs should be prioritized for merge.
    - [ ] verified
    - [x] does not apply
2. The bug has significant impact either through severity, reduction in supportability, or number of users affected.
    - [x] verified
    - [ ] does not apply
3. For branches that are in the Maintenance lifecycle phase:
    - [ ] The bug is a critical fix, no reasonable workaround exists, and a recommendation for upgrade has been ruled out, or 
    - [ ] The bug is a security related bug
    - [x] Branch not in maintenance mode yet (current release + previous release for 90 days after current GA; everything older is in maintenance)
4. The severity field of the bug must be set to accurately reflect criticality.
    - [x] verified
5. The PR was created with the cherry-pick bot OR the PR’s description is well formed with user-focused release notes that state the bug number, impact, cause, and resolution. Where appropriate, it should also contain information about how a user can identify whether a particular cluster is affected.
    - [x] verified

**Comment by jianping-shu** [comment]
/label cherry-pick-approved
/label qe-approved
/lgtm

Tested as comment in Bug 2024751.

**Pull request merged**
