### PR TITLE
WIP: rename provider types to be less generic

### PR DESCRIPTION
**Pull request by joelddiaz**

### CODE REVIEW

**Comment by joelddiaz** [comment]
@dgoodwin is this valuable? I thought about this as I was moving things over to openshift/api, and the names just seemed generic for a repo that can possibly hold other provider types.

**Comment by dgoodwin** [comment]
Seems ok to me.

**Comment by joelddiaz** [comment]
Renaming the fields would break CredentialsRequest pre-rename objects. Abandoning this idea.

**Pull request closed without merging**
