### PR TITLE
OCPBUGS-36029: IBM/go-sdk-core update to v5.17.4

### PR DESCRIPTION
**Pull request by jstuever**
Update IBM/go-sdk-core to v5.17.4 in order to update hashicorp/go-retryablehttp to v0.7.7

### CODE REVIEW

**Comment by jstuever** [comment]
/override ci/prow/security 
Unrelated issue being tracked in other bugs.

**Comment by jianping-shu** [comment]
Verified with cluster-bot build 4.14.0-0.ci.test-2024-07-19-010936-ci-ln-mf72r8t-latest.
AWS STS cluster installed successfully and healthy. Regression tested OCP-36498/
50869/48360/34470/64885.

**Pull request merged**
