### PR TITLE
Bug 2055821: Remove Azure mint mode support as Active Directory Graph API will be sunset

### PR DESCRIPTION
**Pull request by akhil-rane**
Migrate away from depending on the Azure Active Directory Graph API since it will be sunset in June 2022.
- [x] No more mint mode for Azure. So continue supporting passthrough and manual mode as the only supported modes on Azure.
- [x] The implementation is to always mark the Azure root secret as passthrough, and pivot a live running originally-mint cluster to passthrough mode.
- [x] Overwrite existing Secrets with the content found in kube-system/azure-credentials (we can assume this as removing the root creds was never supported in Azure).
- [x] Try to clean up previously minted App Registrations / Service Principals (while the Azure AD Graph API still works), but treat errors as non-fatal (just set a condition on the CredentialsRequest).
- [x] Update test cases.

### CODE REVIEW

**Comment by akhil-rane** [comment]
> Tested w/ [CCO-173 testcases](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitems?query=trello%3ACCO%5C-173), passed

@jianping-shu Do we also need a test wherein a passthrough SP has permissions to delete SPs generated my mint mode?

**Comment by jianping-shu** [comment]
@akhil-rane I think it is already covered by [OCP-47144](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-47144) and [OCP-47159](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-47159)
Pls. let me know if I was wrong or you want to add some scenario more.

**Comment by akhil-rane** [comment]
> @akhil-rane I think it is already covered by [OCP-47144](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-47144) and [OCP-47159](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-47159) Pls. let me know if I was wrong or you want to add some scenario more.

Sorry I missed it. Everything looks good!

**Comment by 2uasimojo** [comment]
> failed to apply

#454

**Pull request merged**
