### PR TITLE
[release-4.13] OCPBUGS-27912: Resolve all outstanding snyk vulnerabilities

### PR DESCRIPTION
**Pull request by dlom**
xref: [CCO-519](https://issues.redhat.com//browse/CCO-519)
/assign @jstuever

### CODE REVIEW

**Comment by dlom** [comment]
/retitle [release-4.13] CCO-519: Resolve all outstanding snyk vulnerabilities

**Comment by dlom** [comment]
/retitle [release-4.13] OCPBUGS-27912: Resolve all outstanding snyk vulnerabilities

**Comment by dlom** [comment]
/retitle [release-4.13] OCPBUGS-27912: Resolve all outstanding snyk vulnerabilities

**Comment by jianping-shu** [comment]
Regression tested with cluster-bot build.
AWS cluster installed successfully.
Regression tests OCP-36498/50869/48360/34470 passed.

**Pull request merged**
