### PR TITLE
go 1.17 changes

### PR DESCRIPTION
**Pull request by joelddiaz**
some harmless changes related to moving to go 1.17 that arise as a
result of running make update-gofmt

### CODE REVIEW

**Comment by joelddiaz** [comment]
/assign @akhil-rane 

this PR is to allow #413 to be cleanly merged

**Comment by joelddiaz** [comment]
FYI @akhil-rane i ended up rebasing this branch on top of the #413 PR to get past the 'make verify' errors.

**Comment by joelddiaz** [comment]
@akhil-rane this should be ready to go. And IIUC, PR #413 will automatically be closed when some bot sees the changes land in our repo.

**Comment by akhil-rane** [comment]
@joelddiaz do we want to update the minimum required version in go.mod [here](https://github.com/openshift/cloud-credential-operator/blob/0e123761e6ebe0b94032bd7fd403b02808f5f6c5/go.mod#L3)?

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Comment by joelddiaz** [comment]
this is purely mechanical PR to get this repo building with go 1.17 with no end-user changes
/label docs-approved
/label px-approved
/label qe-approved

**Pull request merged**
