### PR TITLE
Azure vendoring update

### PR DESCRIPTION
**Pull request by joelddiaz**
update github.com/Azure/azure-sdk-for-go and github.com/Azure/go-autorest vendoring

xref: https://issues.redhat.com/browse/CCO-173

### CODE REVIEW

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Comment by joelddiaz** [comment]
@akhil-rane had to re-base after another PR merged

**Comment by joelddiaz** [comment]
/assign @lwan-wanglin @jeana-redhat @sferich888 
This is just updating some of our Azure golang dependencies. No code / feature changes here.

**Comment by lwan-wanglin** [comment]
run a basic test, no regression found https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/245695/console
/label qe-approved

**Comment by joelddiaz** [comment]
@akhil-rane this needs another lgtm
@sferich888 this needs the px-approved review

**Pull request merged**
