### PR TITLE
vendor: prune vendor tree

### PR DESCRIPTION
**Pull request by sjenning**
Currently the `vendor` tree is 574MB in size.  For comparison, kubernetes/kubernetes `vendor` is 113MB.

I massaged the `Gopkg.toml` and ran `dep prune` and got it to ~~96MB~~50MB.  Compile/fmt/vet times are all improved significantly.

I ran all the make targets to see if anything was missing after the prune.  Awaiting the official testing to make sure everything that was being used is still there.

@joelddiaz

### CODE REVIEW

**Comment by sjenning** [comment]
testplatform indicates CI issue is resolved

/retest

**Comment by sjenning** [comment]
@joelddiaz can I get lgtm too?

**Comment by dgoodwin** [comment]
/lgtm

Thanks for this Seth, nice improvement.

**Pull request merged**
