### PR TITLE
Bump golang.org/x/net from v0.5.0 to v0.7.0

### PR DESCRIPTION
**Pull request by abutcher**
Bump golang.org/x/net from v0.5.0 to v0.7.0 to address:
- https://github.com/openshift/cloud-credential-operator/security/dependabot/7

This change intentionally leaves many references to previous versions of affected modules in `go.sum` as a test. The above dependabot issues may not be closed by this PR and if they are not closed by this PR then I will create a followup similar to https://github.com/openshift/hive/pull/1965 which includes replaces for those versions.

Changes based on https://github.com/openshift/cloud-credential-operator/pull/511 which should be merged first.

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Okay, I don't understand how dependabot is doing whatever it's doing, but if this is all we need to resolve the issues, I'm for it.

/lgtm

**Comment by abutcher** [comment]
Adding labels for vendor bump.

/label docs-approved
/label px-approved
/label qe-approved

**Pull request merged**
