### PR TITLE
[release-4.10] OCPBUGS-2279: Add ccoctl support to create OIDC endpoint with private S3 bucket

### PR DESCRIPTION
**Pull request by abutcher**
Backports #486 to release-4.10.

[OCPBUGS-2279](https://issues.redhat.com/browse/OCPBUGS-2279)

### CODE REVIEW

**Comment by jianping-shu** [comment]
cluster-bot: build openshift/cloud-credential-operator#501
Verified w/ test cases OCP-52105 and OCP-50175, STS clusters were all installed successfully.

**Comment by abutcher** [comment]
Closing and re-opening since I opened this against the wrong base branch.

**Review by 2uasimojo — COMMENTED** [review]
Clean backport except for a couple of minor (and sensible) manual doc syncups.

/lgtm

**Comment by abutcher** [comment]
Noting that I overrode `ci/prow/e2e-aws-ovn` because the job is an orphan of my original PR. Crier gets confused and reports all jobs with the same HEAD SHA together which is why `ci/prow/e2e-aws-ovn` was incorrectly required for this PR. https://coreos.slack.com/archives/CBN38N3MW/p1666195768214879

**Pull request merged**
