### PR TITLE
azure: move away from ADAL and AD Graph

### PR DESCRIPTION
**Pull request by r4f4**
They are being deprecated in December and might be sunset in June 2023.

### CODE REVIEW

**Comment by r4f4** [comment]
I'm making similar changes to the openshift-installer [1]. I marked this as WIP because I'm still investigating why Azure StackCloud authentication is not working through `azidentity`.

[1] https://github.com/openshift/installer/pull/6003

**Comment by abutcher** [comment]
> Didn't you have ongoing work in this vein? 

@2uasimojo This would need to be done as part of https://issues.redhat.com/browse/CCO-235 which is child card of https://issues.redhat.com/browse/CCO-187 but we don't have anything actively ongoing for this.

**Comment by r4f4** [comment]
/retitle azure: move away from ADAL and AD Graph

**Comment by abutcher** [comment]
@jianping-shu I'm not sure that there's anything we need to test here since Mint mode was removed for Azure https://github.com/openshift/cloud-credential-operator/pull/433, could you confirm?

**Comment by abutcher** [comment]
Note that the vendoring that exists for azure-sdk-for-go + azidentity will be useful for implementation of https://github.com/openshift/enhancements/pull/1301

**Comment by jianping-shu** [comment]
@abutcher Agreed.I think some CCO regression tests on Azure should be fine for this PR.

**Comment by jianping-shu** [comment]
Build with Cluster Bot
build openshift/cloud-credential-operator#502

(1)Install IPI cluster with built image
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Flexy-install/164003
Cluster installed successfully 
jianpingshu@jshu-mac aws % oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.12.0-0.ci.test-2022-12-13-013707-ci-ln-9h1trgk-latest   True        False         3h7m    Cluster version is 4.12.0-0.ci.test-2022-12-13-013707-ci-ln-9h1trgk-latest

(2)Run Golang automation CCO cases, all passed
OCP-34470
OCP-45219
OCP-45975
OCP-31768
OCP-50869
OCP-53283

(3)Upgrade to 4.12.0-rc.4 successfully
jianpingshu@jshu-mac openshift-tests-private % oc get clusterversion   
NAME      VERSION       AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.12.0-rc.4   True        False         11m     Cluster version is 4.12.0-rc.4

**Comment by abutcher** [comment]
@jeana-redhat @davemulford Seeing `docs-approved` and `px-approved` labels for this PR. There is no functional change that would require docs or px changes since we do not currently have Azure mint mode. Please reach out if you have any questions, thanks!

**Pull request merged**
