### PR TITLE
CCO-440: Bump k8s deps to 0.28.3

### PR DESCRIPTION
**Pull request by 2uasimojo**
[CCO-440](https://issues.redhat.com//browse/CCO-440)

**NOTE:** Adapted hacks from [here](https://github.com/soltysh/client-go/blob/cbc4a19d30ca455590018ea83250d5bdd4636f80/hack/update-codegen.sh#L13-L24) to make this work.

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/retest

I don't know how to look at these failures to see if they're flakes. If this keeps failing I'll probably need some help with that.

**Comment by jstuever** [comment]
Not a flake. Leader election is using `configmapsleases`, which is not available in 1.28. We will need to migrate to `resourcelock.LeasesResourceLock`, which I will do in another PR.

**Comment by 2uasimojo** [comment]
> Not a flake. Leader election is using `configmapsleases`, which is not available in 1.28. We will need to migrate to `resourcelock.LeasesResourceLock`, which I will do in another PR.

Done in #627.

**Comment by 2uasimojo** [comment]
> tide Pending — Not mergeable. Needs acknowledge-critical-fixes-only label.

I think we decided it was acceptable to wait until next week to land this.

**Comment by 2uasimojo** [comment]
/label acknowledge-critical-fixes-only

Per @wallylewis in CCO-440 we're allowed to do this for k8s bumps.

**Pull request merged**
