### PR TITLE
WIP: AzureStack support

### PR DESCRIPTION
**Pull request by joelddiaz**
- [x] update Azure dependencies (not strictly necessary)
- [x] vendor in updated openshift/api (for AzureStack constants)
- [x] Extend the Azure client setup to look into the openshift-config/cloud-provider-config configMap to detect when the cluster is running on AzureStack
- [x] Read in the endpoints JSON and set the appropriate environment variable before running throught he Azure SDK client configuration.  (still waiting on what the actual ConfigMap will look like)

xref: https://issues.redhat.com/browse/CCO-102

### CODE REVIEW

**Comment by joelddiaz** [comment]
/hold
temporarily vendoring patrickdillon/api@azurestack until openshift/api#860 merges so we can then do a real vendor

**Comment by dgoodwin** [comment]
Changed the x-ref to a card I made rather than the epic.

**Comment by patrickdillon** [comment]
API PR has merged

**Comment by joelddiaz** [comment]
cc @akhil-rane ^ API PR merged message

**Comment by akhil-rane** [comment]
> cc @akhil-rane ^ API PR merged message

sounds good I will take a look

**Comment by patrickdillon** [comment]
It looks like you were able to work with the cloud provider config configmap, but in case you were not aware the work is captured here: https://github.com/openshift/installer/pull/5042. Hoping to merge this today/ASAP.

**Comment by gregsheremeta** [comment]
/close

all new platforms use Manual mode. See https://github.com/openshift/enhancements/pull/709

**Pull request closed without merging**
