### PR TITLE
update sts docs to reference ccoctl where appropriate

### PR DESCRIPTION
**Pull request by joelddiaz**

### CODE REVIEW

**Comment by joelddiaz** [comment]
/assign @akhil-rane @jeana-redhat @lwan-wanglin @sferich888 
just cleaning up internal docs to be more up-to-date with new ccoctl tool

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Comment by joelddiaz** [comment]
just some docs clarification
/label px-approved

**Pull request merged**
