### PR TITLE
[release-4.15] OCPBUGS-37461: Set required-scc for openshift workloads

### PR DESCRIPTION
**Pull request by kramaranya**
[OCPBUGS-37461](https://issues.redhat.com/browse/OCPBUGS-37461)

Cherry-pick of #681

### CODE REVIEW

**Comment by jstuever** [comment]
/override ci/prow/security
This is being addressed in another existing Jira big.

**Comment by huangmingxia** [comment]
/label cherry-pick-approved

Verified pass with image registry.build05.ci.openshift.org/ci-ln-hxxlz2b/release:latest on 4.15 with below cluster type.

- AWS
- AWS STS
- Azure
- Entra Workload ID
- GCP
- GCP workload ID

**Pull request merged**
